/**
 * Synthesize phase1.jsonl + phase2.jsonl for the streaming demo.
 *
 * Phase 1: 500 stock rows with curated real ticker symbols, varied prices/
 * volumes/sectors, emitted as OpenAI Responses-format SSE deltas with
 * realistic chunk sizes (5–15 chars) and timing (~30s total span). The
 * timing is modeled after captured gpt-5 streams: ~25ms inter-chunk gaps
 * with occasional 100–300ms pauses to mimic LLM "thinking" stutters.
 *
 * Phase 2: 100 batches of price updates over 10s as a starter pattern.
 * The full 90s update sequence is regenerated by `generate-phase2.ts`.
 *
 * Why synthesized? Real LLM captures (gpt-5, gpt-4o) reliably fail to
 * produce 500 varied rows in a single response — they either truncate,
 * repeat values, or wrap output in markdown. The capture-phase1.ts script
 * stays in the repo for anyone who wants to try, but this synthesis path
 * is the canonical demo recording: deterministic, reproducible, varied.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname ?? __dirname, "..");
const OUT_DIR = join(ROOT, "src", "recordings");
mkdirSync(OUT_DIR, { recursive: true });

const ROW_COUNT = 500;
const PHASE1_DURATION_S = 30;
const SEED = 0xc0ffee;

function mulberry32(seed: number) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rng = mulberry32(SEED);
const choice = <T>(arr: readonly T[]): T =>
  arr[Math.floor(rng() * arr.length)];

interface CompanySeed {
  symbol: string;
  name: string;
  sector: string;
  /** Approximate price band so the data feels right per company. */
  priceLow: number;
  priceHigh: number;
}

// Real-ish blue-chip companies grouped roughly by sector.
const SEEDS: CompanySeed[] = [
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technology", priceLow: 180, priceHigh: 220 },
  { symbol: "MSFT", name: "Microsoft Corp.", sector: "Technology", priceLow: 350, priceHigh: 420 },
  { symbol: "GOOGL", name: "Alphabet Inc.", sector: "Technology", priceLow: 130, priceHigh: 165 },
  { symbol: "META", name: "Meta Platforms", sector: "Technology", priceLow: 380, priceHigh: 470 },
  { symbol: "NVDA", name: "NVIDIA Corp.", sector: "Technology", priceLow: 700, priceHigh: 900 },
  { symbol: "ORCL", name: "Oracle Corp.", sector: "Technology", priceLow: 110, priceHigh: 140 },
  { symbol: "CRM", name: "Salesforce", sector: "Technology", priceLow: 240, priceHigh: 290 },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "Technology", priceLow: 470, priceHigh: 580 },
  { symbol: "INTC", name: "Intel Corp.", sector: "Technology", priceLow: 30, priceHigh: 45 },
  { symbol: "AMD", name: "Advanced Micro Devices", sector: "Technology", priceLow: 130, priceHigh: 180 },
  { symbol: "AVGO", name: "Broadcom Inc.", sector: "Technology", priceLow: 1100, priceHigh: 1400 },
  { symbol: "CSCO", name: "Cisco Systems", sector: "Technology", priceLow: 45, priceHigh: 58 },
  { symbol: "QCOM", name: "Qualcomm", sector: "Technology", priceLow: 140, priceHigh: 175 },
  { symbol: "IBM", name: "IBM Corp.", sector: "Technology", priceLow: 150, priceHigh: 190 },
  { symbol: "TXN", name: "Texas Instruments", sector: "Technology", priceLow: 160, priceHigh: 195 },
  { symbol: "AMZN", name: "Amazon.com", sector: "Consumer", priceLow: 140, priceHigh: 180 },
  { symbol: "TSLA", name: "Tesla Inc.", sector: "Consumer", priceLow: 200, priceHigh: 260 },
  { symbol: "WMT", name: "Walmart Inc.", sector: "Consumer", priceLow: 60, priceHigh: 75 },
  { symbol: "HD", name: "Home Depot", sector: "Consumer", priceLow: 320, priceHigh: 390 },
  { symbol: "MCD", name: "McDonald's", sector: "Consumer", priceLow: 270, priceHigh: 310 },
  { symbol: "NKE", name: "Nike Inc.", sector: "Consumer", priceLow: 90, priceHigh: 115 },
  { symbol: "SBUX", name: "Starbucks", sector: "Consumer", priceLow: 90, priceHigh: 110 },
  { symbol: "COST", name: "Costco Wholesale", sector: "Consumer", priceLow: 700, priceHigh: 850 },
  { symbol: "TGT", name: "Target Corp.", sector: "Consumer", priceLow: 140, priceHigh: 175 },
  { symbol: "LOW", name: "Lowe's Companies", sector: "Consumer", priceLow: 220, priceHigh: 270 },
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Financials", priceLow: 175, priceHigh: 220 },
  { symbol: "BAC", name: "Bank of America", sector: "Financials", priceLow: 33, priceHigh: 45 },
  { symbol: "WFC", name: "Wells Fargo", sector: "Financials", priceLow: 45, priceHigh: 58 },
  { symbol: "GS", name: "Goldman Sachs", sector: "Financials", priceLow: 380, priceHigh: 460 },
  { symbol: "MS", name: "Morgan Stanley", sector: "Financials", priceLow: 90, priceHigh: 115 },
  { symbol: "C", name: "Citigroup", sector: "Financials", priceLow: 55, priceHigh: 70 },
  { symbol: "BLK", name: "BlackRock Inc.", sector: "Financials", priceLow: 760, priceHigh: 920 },
  { symbol: "AXP", name: "American Express", sector: "Financials", priceLow: 200, priceHigh: 250 },
  { symbol: "V", name: "Visa Inc.", sector: "Financials", priceLow: 250, priceHigh: 290 },
  { symbol: "MA", name: "Mastercard", sector: "Financials", priceLow: 420, priceHigh: 490 },
  { symbol: "UNH", name: "UnitedHealth", sector: "Healthcare", priceLow: 480, priceHigh: 580 },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", priceLow: 150, priceHigh: 175 },
  { symbol: "LLY", name: "Eli Lilly", sector: "Healthcare", priceLow: 700, priceHigh: 850 },
  { symbol: "PFE", name: "Pfizer Inc.", sector: "Healthcare", priceLow: 27, priceHigh: 38 },
  { symbol: "ABBV", name: "AbbVie Inc.", sector: "Healthcare", priceLow: 150, priceHigh: 180 },
  { symbol: "MRK", name: "Merck & Co.", sector: "Healthcare", priceLow: 100, priceHigh: 130 },
  { symbol: "TMO", name: "Thermo Fisher", sector: "Healthcare", priceLow: 510, priceHigh: 610 },
  { symbol: "ABT", name: "Abbott Labs", sector: "Healthcare", priceLow: 105, priceHigh: 130 },
  { symbol: "DHR", name: "Danaher Corp.", sector: "Healthcare", priceLow: 230, priceHigh: 280 },
  { symbol: "BMY", name: "Bristol-Myers", sector: "Healthcare", priceLow: 45, priceHigh: 60 },
  { symbol: "XOM", name: "ExxonMobil", sector: "Energy", priceLow: 100, priceHigh: 125 },
  { symbol: "CVX", name: "Chevron Corp.", sector: "Energy", priceLow: 145, priceHigh: 175 },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energy", priceLow: 100, priceHigh: 125 },
  { symbol: "SLB", name: "Schlumberger", sector: "Energy", priceLow: 42, priceHigh: 56 },
  { symbol: "EOG", name: "EOG Resources", sector: "Energy", priceLow: 110, priceHigh: 140 },
  { symbol: "MPC", name: "Marathon Petroleum", sector: "Energy", priceLow: 145, priceHigh: 180 },
  { symbol: "PSX", name: "Phillips 66", sector: "Energy", priceLow: 130, priceHigh: 165 },
  { symbol: "VLO", name: "Valero Energy", sector: "Energy", priceLow: 130, priceHigh: 165 },
  { symbol: "CAT", name: "Caterpillar", sector: "Industrials", priceLow: 270, priceHigh: 340 },
  { symbol: "BA", name: "Boeing Co.", sector: "Industrials", priceLow: 175, priceHigh: 220 },
  { symbol: "HON", name: "Honeywell", sector: "Industrials", priceLow: 195, priceHigh: 230 },
  { symbol: "UNP", name: "Union Pacific", sector: "Industrials", priceLow: 230, priceHigh: 275 },
  { symbol: "UPS", name: "United Parcel Service", sector: "Industrials", priceLow: 135, priceHigh: 165 },
  { symbol: "DE", name: "Deere & Co.", sector: "Industrials", priceLow: 370, priceHigh: 450 },
  { symbol: "RTX", name: "RTX Corp.", sector: "Industrials", priceLow: 95, priceHigh: 120 },
  { symbol: "LMT", name: "Lockheed Martin", sector: "Industrials", priceLow: 440, priceHigh: 530 },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrials", priceLow: 150, priceHigh: 190 },
  { symbol: "LIN", name: "Linde plc", sector: "Materials", priceLow: 420, priceHigh: 500 },
  { symbol: "APD", name: "Air Products", sector: "Materials", priceLow: 240, priceHigh: 290 },
  { symbol: "SHW", name: "Sherwin-Williams", sector: "Materials", priceLow: 295, priceHigh: 360 },
  { symbol: "ECL", name: "Ecolab Inc.", sector: "Materials", priceLow: 220, priceHigh: 265 },
  { symbol: "FCX", name: "Freeport-McMoRan", sector: "Materials", priceLow: 38, priceHigh: 52 },
  { symbol: "NEM", name: "Newmont Corp.", sector: "Materials", priceLow: 35, priceHigh: 50 },
  { symbol: "NEE", name: "NextEra Energy", sector: "Utilities", priceLow: 65, priceHigh: 85 },
  { symbol: "DUK", name: "Duke Energy", sector: "Utilities", priceLow: 95, priceHigh: 115 },
  { symbol: "SO", name: "Southern Co.", sector: "Utilities", priceLow: 75, priceHigh: 90 },
  { symbol: "AEP", name: "American Electric", sector: "Utilities", priceLow: 80, priceHigh: 100 },
  { symbol: "PLD", name: "Prologis Inc.", sector: "RealEstate", priceLow: 110, priceHigh: 140 },
  { symbol: "AMT", name: "American Tower", sector: "RealEstate", priceLow: 195, priceHigh: 240 },
  { symbol: "EQIX", name: "Equinix Inc.", sector: "RealEstate", priceLow: 760, priceHigh: 900 },
  { symbol: "CCI", name: "Crown Castle", sector: "RealEstate", priceLow: 95, priceHigh: 120 },
  { symbol: "DIS", name: "Walt Disney Co.", sector: "Communication", priceLow: 90, priceHigh: 115 },
  { symbol: "CMCSA", name: "Comcast Corp.", sector: "Communication", priceLow: 38, priceHigh: 50 },
  { symbol: "T", name: "AT&T Inc.", sector: "Communication", priceLow: 17, priceHigh: 24 },
  { symbol: "VZ", name: "Verizon", sector: "Communication", priceLow: 38, priceHigh: 48 },
  { symbol: "NFLX", name: "Netflix Inc.", sector: "Communication", priceLow: 580, priceHigh: 720 },
];

// Need 500 rows; expand by suffixing variants.
const VARIANT_SUFFIXES = ["", ".A", ".B", ".C", ".D", "I", "II", "III"];
const VARIANT_NAME_MODIFIERS = [
  "",
  " Holdings",
  " Group",
  " Trust",
  " Partners",
  " Enterprises",
  " Industries",
];

const allRows: Array<{
  symbol: string;
  name: string;
  last: number;
  change_pct: number;
  volume: number;
  sector: string;
  last_update: string;
}> = [];

const MARKET_HOURS = [
  ["09", "30"],
  ["09", "45"],
  ["10", "00"],
  ["10", "15"],
  ["10", "30"],
  ["11", "00"],
  ["11", "30"],
  ["12", "00"],
  ["13", "00"],
  ["14", "00"],
  ["14", "30"],
  ["15", "00"],
  ["15", "30"],
  ["15", "45"],
];

for (let i = 0; i < ROW_COUNT; i++) {
  const seed = SEEDS[i % SEEDS.length];
  const variantIdx = Math.floor(i / SEEDS.length);
  const symbolSuffix = VARIANT_SUFFIXES[variantIdx % VARIANT_SUFFIXES.length];
  const nameSuffix =
    VARIANT_NAME_MODIFIERS[variantIdx % VARIANT_NAME_MODIFIERS.length];
  const symbol = (seed.symbol + symbolSuffix).slice(0, 7);
  const name = nameSuffix ? `${seed.name}${nameSuffix}` : seed.name;
  const span = seed.priceHigh - seed.priceLow;
  const last = Number((seed.priceLow + rng() * span).toFixed(2));
  const change_pct = Number((rng() * 10 - 5).toFixed(2));
  const volume = Math.floor(100_000 + rng() * 99_900_000);
  const [hh, mm] = choice(MARKET_HOURS);
  const ss = String(Math.floor(rng() * 60)).padStart(2, "0");
  allRows.push({
    symbol,
    name,
    last,
    change_pct,
    volume,
    sector: seed.sector,
    last_update: `${hh}:${mm}:${ss}`,
  });
}

const fullJson = JSON.stringify(allRows);

// Chunk into realistic SSE deltas with stutter timing.
const phase1Lines: string[] = [];
let t = 0.5;
phase1Lines.push(JSON.stringify({ t, type: "response.created" }));

const expectedChunks = Math.floor(fullJson.length / 9);
const avgInterval = PHASE1_DURATION_S / expectedChunks;

let pos = 0;
let streamingT = 1.0;
while (pos < fullJson.length) {
  const size = 5 + Math.floor(rng() * 11);
  const delta = fullJson.slice(pos, pos + size);
  let interval = avgInterval * (0.5 + rng());
  // Rare stutters that mimic LLM "thinking" pauses.
  if (rng() < 0.005) interval += 0.05 + rng() * 0.15;
  streamingT += interval;
  phase1Lines.push(
    JSON.stringify({
      t: Number(streamingT.toFixed(3)),
      type: "response.output_text.delta",
      delta,
    }),
  );
  pos += size;
}

streamingT += 0.15;
phase1Lines.push(
  JSON.stringify({
    t: Number(streamingT.toFixed(3)),
    type: "response.output_text.done",
  }),
);
streamingT += 0.05;
phase1Lines.push(
  JSON.stringify({
    t: Number(streamingT.toFixed(3)),
    type: "response.completed",
  }),
);

writeFileSync(join(OUT_DIR, "phase1.jsonl"), phase1Lines.join("\n") + "\n");

const phase1End = streamingT;

// ---------- Phase 2 starter (regenerated by generate-phase2 for full sequence) ----------

const phase2Lines: string[] = [];
for (let step = 0; step < 100; step++) {
  const vt = phase1End + step * 0.1;
  const row = allRows[step % allRows.length];
  const startPrice = (() => {
    const s = SEEDS.find((x) => row.symbol.startsWith(x.symbol));
    return s ? (s.priceLow + s.priceHigh) / 2 : row.last;
  })();
  const drift = (rng() - 0.5) * startPrice * 0.005;
  row.last = Number(Math.max(0.01, row.last + drift).toFixed(2));
  row.change_pct = Number(
    (((row.last - startPrice) / startPrice) * 100).toFixed(2),
  );
  row.volume += Math.floor(rng() * 100_000) + 1000;
  const totalSeconds = Math.floor(vt);
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  row.last_update = `14:${String(30 + minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`;
  phase2Lines.push(
    JSON.stringify({
      t: Number(vt.toFixed(3)),
      patches: [
        {
          id: row.symbol,
          last: row.last,
          change_pct: row.change_pct,
          volume: row.volume,
          last_update: row.last_update,
        },
      ],
    }),
  );
}

writeFileSync(join(OUT_DIR, "phase2.jsonl"), phase2Lines.join("\n") + "\n");

console.log(
  `[make-dev-fixture] wrote ${phase1Lines.length} phase1 lines (${ROW_COUNT} rows, ${phase1End.toFixed(1)}s span) and ${phase2Lines.length} phase2 starter lines`,
);
console.log(
  `[make-dev-fixture] regenerate the full phase 2 sequence with: pnpm generate-phase2`,
);
