import { readFileSync } from "node:fs";
import { join } from "node:path";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Bench results — pretable",
  description:
    "Comparative bench results for pretable vs gridalpha vs gridbeta on wrapped-text scroll and streaming row stability.",
};

interface Evidence {
  adapterId: string;
  scenarioId: string;
  metrics: {
    scroll_frame_p95_ms?: number;
    row_height_error_p95_px?: number;
    [k: string]: unknown;
  };
}

interface Hypothesis {
  id: string;
  status: string;
  summary: string;
  evidence: Evidence[];
}

interface MilestoneFile {
  hypotheses: Hypothesis[];
}

const REPO = "cacheplane/pretable";
const ADAPTER_ORDER = ["pretable", "gridalpha", "gridbeta"] as const;

function repoRootRelative(...segments: string[]): string {
  // app/bench/page.tsx → ../../../  → apps/website root → ../../  → repo root
  return join(process.cwd(), "..", "..", ...segments);
}

function loadH1(): {
  rows: { adapter: string; p95Ms: number; rhePx: number }[];
  filename: string;
} {
  const filename = "status/milestones/2026-05-01-h1-satisfied.hypotheses.json";
  const raw = readFileSync(repoRootRelative(filename), "utf8");
  const data = JSON.parse(raw) as MilestoneFile;
  const h1 = data.hypotheses.find((h) => h.id === "H1");
  if (!h1) throw new Error("H1 not found in milestone file");
  const rows = ADAPTER_ORDER.map((adapter) => {
    const ev = h1.evidence.find(
      (e) => e.adapterId === adapter && e.scenarioId === "S2",
    );
    if (!ev) throw new Error(`No H1/S2 evidence for ${adapter}`);
    const p95 = ev.metrics.scroll_frame_p95_ms;
    const rhe = ev.metrics.row_height_error_p95_px;
    if (p95 == null || rhe == null) {
      throw new Error(`Missing metrics for ${adapter}`);
    }
    return { adapter, p95Ms: p95, rhePx: rhe };
  });
  return { rows, filename };
}

function loadStreamingSummary(): string {
  const filename =
    "status/milestones/2026-05-01-streaming-revalidated.hypotheses.json";
  const raw = readFileSync(repoRootRelative(filename), "utf8");
  const data = JSON.parse(raw) as MilestoneFile;
  const h15 = data.hypotheses.find((h) => h.id === "H15");
  return h15?.summary ?? "";
}

export default function BenchPage() {
  const { rows: h1Rows, filename: h1File } = loadH1();
  const streamingSummary = loadStreamingSummary();
  const streamingFile =
    "status/milestones/2026-05-01-streaming-revalidated.hypotheses.json";

  const fastest = h1Rows.reduce((min, r) => (r.p95Ms < min.p95Ms ? r : min));
  const slowest = h1Rows.reduce((max, r) => (r.p95Ms > max.p95Ms ? r : max));
  const speedup = (slowest.p95Ms / fastest.p95Ms).toFixed(1);

  return (
    <article className="prose">
      <h1 className="font-display text-[44px] leading-[1.05] tracking-[-0.025em] text-text-primary">
        Bench results
      </h1>
      <p className="mt-4 max-w-[60ch] text-[16px] leading-[1.6] text-text-secondary">
        These numbers anchor every claim on the homepage. Generated by running
        the same dataset through{" "}
        <a
          className="text-accent underline-offset-2 hover:underline"
          href={`https://github.com/${REPO}/tree/main/apps/bench`}
        >
          <code>apps/bench</code>
        </a>{" "}
        — pretable, gridalpha, gridbeta — measuring scroll frame timings and
        row-height fidelity. All raw data is in the repo; the page below is a
        rendered view of two milestone JSON files.
      </p>

      <h2 className="mt-12 font-display text-[28px] tracking-[-0.02em] text-text-primary">
        H1 — wrapped-text scroll
      </h2>
      <p className="mt-3 text-[15px] leading-[1.6] text-text-secondary">
        Scenario <code>S2</code> (3,000 rows, wrapped multilingual messages,
        scroll script). Frame p95 measured via Performance Observer; row-height
        error measured by comparing the engine's planned row height against the
        actual rendered DOM height. Lower is better for both.
      </p>

      <table className="mt-6 w-full table-fixed border-collapse text-left text-[14px]">
        <thead>
          <tr className="border-b border-rule text-text-muted">
            <th className="py-3 font-mono text-[11px] uppercase tracking-[0.14em]">
              Adapter
            </th>
            <th className="py-3 font-mono text-[11px] uppercase tracking-[0.14em]">
              Frame p95 (ms)
            </th>
            <th className="py-3 font-mono text-[11px] uppercase tracking-[0.14em]">
              Row height error (px)
            </th>
            <th className="py-3 font-mono text-[11px] uppercase tracking-[0.14em]">
              Verdict
            </th>
          </tr>
        </thead>
        <tbody>
          {h1Rows.map((r) => (
            <tr
              className="border-b border-rule-soft text-text-primary"
              key={r.adapter}
            >
              <td className="py-3 font-mono text-[13px] font-semibold">
                {r.adapter}
              </td>
              <td className="py-3 font-mono text-[13px] tabular-nums">
                {r.p95Ms.toFixed(1)}
              </td>
              <td className="py-3 font-mono text-[13px] tabular-nums">
                {r.rhePx}
              </td>
              <td className="py-3 text-[13px] text-text-secondary">
                {r.adapter === "pretable" && "fastest + zero clipping"}
                {r.adapter === "gridalpha" &&
                  `${(r.p95Ms / fastest.p95Ms).toFixed(1)}× slower; clips wrapped content (${r.rhePx}px)`}
                {r.adapter === "gridbeta" && "fastest tied; needs DIY assembly"}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <p className="mt-6 text-[15px] leading-[1.6] text-text-secondary">
        <strong className="text-text-primary">{speedup}× faster</strong> than{" "}
        gridalpha on the same dataset, with zero row-height error. gridbeta
        matches the speed but is a virtualization primitive — you assemble
        sort/filter/selection yourself. gridalpha is a full grid but clips
        wrapped content to a single line at hypothesis scale.
      </p>

      <h2 className="mt-12 font-display text-[28px] tracking-[-0.02em] text-text-primary">
        H15 — streaming row stability
      </h2>
      <p className="mt-3 text-[15px] leading-[1.6] text-text-secondary">
        {streamingSummary}
      </p>

      <h2 className="mt-12 font-display text-[28px] tracking-[-0.02em] text-text-primary">
        Methodology
      </h2>
      <ul className="mt-3 list-disc pl-6 text-[15px] leading-[1.65] text-text-secondary">
        <li>
          <strong className="text-text-primary">
            Same dataset, same script.
          </strong>{" "}
          Each adapter runs the canonical scenario from{" "}
          <code>@pretable-internal/scenario-data</code> through identical
          interaction plans. The harness is in{" "}
          <code>@pretable-internal/bench-runner</code>.
        </li>
        <li>
          <strong className="text-text-primary">Repeated-run medians.</strong> 5
          samples per (adapter, scenario, script) tuple. Reported value is the
          median; min and max are in the raw JSON.
        </li>
        <li>
          <strong className="text-text-primary">
            No per-adapter optimizations.
          </strong>{" "}
          Each adapter uses its library's idiomatic streaming pattern:
          gridalpha's <code>applyTransaction</code>, gridbeta's
          <code> useVirtualizer</code> + setState, pretable's RAF-batched{" "}
          <code>grid.applyTransaction</code> via{" "}
          <code>@pretable/stream-adapter</code>.
        </li>
        <li>
          <strong className="text-text-primary">Wedge integrity:</strong> the
          pretable adapter renders the same{" "}
          <a
            className="text-accent underline-offset-2 hover:underline"
            href="/docs/grid/pretable-surface"
          >
            <code>&lt;PretableSurface&gt;</code>
          </a>{" "}
          the website's homepage hero uses. What we measure is what you ship.
        </li>
      </ul>

      <h2 className="mt-12 font-display text-[28px] tracking-[-0.02em] text-text-primary">
        Run it yourself
      </h2>
      <p className="mt-3 text-[15px] leading-[1.6] text-text-secondary">
        The bench is part of the open-source repo. Clone, install, run:
      </p>
      <pre className="mt-4 overflow-x-auto rounded-[4px] bg-bg-card p-4 font-mono text-[13px] text-text-primary">
        <code>{`git clone https://github.com/${REPO}.git
cd pretable
pnpm install
pnpm bench:matrix      # produces status/runsets/<timestamp>.hypotheses.json`}</code>
      </pre>
      <p className="mt-4 text-[15px] leading-[1.6] text-text-secondary">
        For the full contributor walkthrough, see{" "}
        <a
          className="text-accent underline-offset-2 hover:underline"
          href={`https://github.com/${REPO}/blob/main/apps/bench/README.md`}
        >
          <code>apps/bench/README.md</code>
        </a>
        .
      </p>

      <h2 className="mt-12 font-display text-[28px] tracking-[-0.02em] text-text-primary">
        Raw data
      </h2>
      <ul className="mt-3 list-disc pl-6 text-[15px] leading-[1.65] text-text-secondary">
        <li>
          <a
            className="text-accent underline-offset-2 hover:underline"
            href={`https://github.com/${REPO}/blob/main/${h1File}`}
          >
            <code>{h1File}</code>
          </a>{" "}
          — H1 wrapped-text scroll evidence
        </li>
        <li>
          <a
            className="text-accent underline-offset-2 hover:underline"
            href={`https://github.com/${REPO}/blob/main/${streamingFile}`}
          >
            <code>{streamingFile}</code>
          </a>{" "}
          — H15 streaming row stability + four other hypotheses
        </li>
        <li>
          <a
            className="text-accent underline-offset-2 hover:underline"
            href={`https://github.com/${REPO}/tree/main/status/milestones`}
          >
            <code>status/milestones/</code>
          </a>{" "}
          — all milestone JSONs (H1, H6–H12 interaction, S3 column
          virtualization)
        </li>
      </ul>
    </article>
  );
}
