// Generated by `pnpm examples:gen`. Do not edit.
// Add an example by creating content/examples/<slug>/example.ts,
// default-exporting an ExampleMeta (see lib/docs/examples/define.ts).
// An optional demo.tsx must default-export a props-free component.

import type { ComponentType } from "react";

import type { ExampleId } from "./registry.generated";

import groupingPanelDemo from "../../../content/examples/grouping-panel/demo";
import headlessCustomRendererDemo from "../../../content/examples/headless-custom-renderer/demo";
import streamingChatGridDemo from "../../../content/examples/streaming-chat-grid/demo";

export const exampleDemos: Partial<Record<ExampleId, ComponentType>> = {
  "grouping-panel": groupingPanelDemo,
  "headless-custom-renderer": headlessCustomRendererDemo,
  "streaming-chat-grid": streamingChatGridDemo,
};
