// Generated by `pnpm examples:gen`. Do not edit.
// Add an example by creating content/examples/<slug>/example.ts,
// default-exporting an ExampleMeta (see lib/docs/examples/define.ts).
// An optional demo.tsx must default-export a props-free component.

import type { ComponentType } from "react";

import type { ExampleId } from "./registry.generated";

import asyncCellEditingDemo from "../../../content/examples/async-cell-editing/demo";
import cellPresentationsDemo from "../../../content/examples/cell-presentations/demo";
import columnFiltersDemo from "../../../content/examples/column-filters/demo";
import columnLayoutDemo from "../../../content/examples/column-layout/demo";
import customCellEditorDemo from "../../../content/examples/custom-cell-editor/demo";
import customThemeDemo from "../../../content/examples/custom-theme/demo";
import darkModeToggleDemo from "../../../content/examples/dark-mode-toggle/demo";
import firstGridDemo from "../../../content/examples/first-grid/demo";
import groupExpansionControlDemo from "../../../content/examples/group-expansion-control/demo";
import groupingPanelDemo from "../../../content/examples/grouping-panel/demo";
import headlessCustomRendererDemo from "../../../content/examples/headless-custom-renderer/demo";
import keyboardNavigationDemo from "../../../content/examples/keyboard-navigation/demo";
import multiColumnSortDemo from "../../../content/examples/multi-column-sort/demo";
import partialRowStreamDemo from "../../../content/examples/partial-row-stream/demo";
import pasteGeometryDemo from "../../../content/examples/paste-geometry/demo";
import rangeSelectionDemo from "../../../content/examples/range-selection/demo";
import streamingChatGridDemo from "../../../content/examples/streaming-chat-grid/demo";
import weightedAverageAggregatorDemo from "../../../content/examples/weighted-average-aggregator/demo";

export const exampleDemos: Partial<Record<ExampleId, ComponentType>> = {
  "async-cell-editing": asyncCellEditingDemo,
  "cell-presentations": cellPresentationsDemo,
  "column-filters": columnFiltersDemo,
  "column-layout": columnLayoutDemo,
  "custom-cell-editor": customCellEditorDemo,
  "custom-theme": customThemeDemo,
  "dark-mode-toggle": darkModeToggleDemo,
  "first-grid": firstGridDemo,
  "group-expansion-control": groupExpansionControlDemo,
  "grouping-panel": groupingPanelDemo,
  "headless-custom-renderer": headlessCustomRendererDemo,
  "keyboard-navigation": keyboardNavigationDemo,
  "multi-column-sort": multiColumnSortDemo,
  "partial-row-stream": partialRowStreamDemo,
  "paste-geometry": pasteGeometryDemo,
  "range-selection": rangeSelectionDemo,
  "streaming-chat-grid": streamingChatGridDemo,
  "weighted-average-aggregator": weightedAverageAggregatorDemo,
};
