// Generated by `pnpm examples:gen`. Do not edit.
// Add an example by creating content/examples/<slug>/example.ts,
// default-exporting an ExampleMeta (see lib/docs/examples/define.ts).
// An optional demo.tsx must default-export a props-free component.

import type { ComponentType } from "react";

import type { ExampleId } from "./registry.generated";

export const exampleDemos: Partial<Record<ExampleId, ComponentType>> = {};
