// Generated by `pnpm examples:gen`. Do not edit.
// Add an example by creating content/examples/<slug>/example.ts,
// default-exporting an ExampleMeta (see lib/docs/examples/define.ts).
// An optional demo.tsx must default-export a props-free component.

import asyncCellEditing from "../../../content/examples/async-cell-editing/example";
import cellPresentations from "../../../content/examples/cell-presentations/example";
import columnFilters from "../../../content/examples/column-filters/example";
import firstGrid from "../../../content/examples/first-grid/example";
import groupingPanel from "../../../content/examples/grouping-panel/example";
import headlessCustomRenderer from "../../../content/examples/headless-custom-renderer/example";
import rangeSelection from "../../../content/examples/range-selection/example";
import streamingChatGrid from "../../../content/examples/streaming-chat-grid/example";

export const exampleRegistry = {
  "async-cell-editing": {
    meta: asyncCellEditing,
    hasDemo: true,
  },
  "cell-presentations": {
    meta: cellPresentations,
    hasDemo: true,
  },
  "column-filters": {
    meta: columnFilters,
    hasDemo: true,
  },
  "first-grid": {
    meta: firstGrid,
    hasDemo: true,
  },
  "grouping-panel": {
    meta: groupingPanel,
    hasDemo: true,
  },
  "headless-custom-renderer": {
    meta: headlessCustomRenderer,
    hasDemo: true,
  },
  "range-selection": {
    meta: rangeSelection,
    hasDemo: true,
  },
  "streaming-chat-grid": {
    meta: streamingChatGrid,
    hasDemo: true,
  },
} as const;

export type ExampleId = keyof typeof exampleRegistry;
