export interface HeroEvent {
  id: string;
  timestamp: string;
  kind: string;
  message: string;
  status: "ok" | "warn" | "error";
  latencyMs: number;
}

const baseDate = new Date("2026-05-02T18:42:00Z");

function formatTime(offsetSeconds: number): string {
  const ts = new Date(baseDate.getTime() + offsetSeconds * 1000);
  return ts.toISOString().slice(11, 19);
}

export const heroEventLog: readonly HeroEvent[] = [
  {
    id: "h-001",
    timestamp: formatTime(0),
    kind: "user.created",
    message: "token-204 ✓",
    status: "ok",
    latencyMs: 12,
  },
  {
    id: "h-002",
    timestamp: formatTime(1),
    kind: "order.placed",
    message: "Bonjour depuis Pretable token-231 — customer-facing · 3 items",
    status: "ok",
    latencyMs: 9,
  },
  {
    id: "h-003",
    timestamp: formatTime(2),
    kind: "payment.captured",
    message: "stripe.events ✓",
    status: "ok",
    latencyMs: 7,
  },
  {
    id: "h-004",
    timestamp: formatTime(3),
    kind: "cache.miss",
    message: "region:us-west-2",
    status: "error",
    latencyMs: 23,
  },
  {
    id: "h-005",
    timestamp: formatTime(4),
    kind: "webhook.delivered",
    message: "Hola desde Pretable token-202 — stripe.events · retry 1",
    status: "ok",
    latencyMs: 11,
  },
  {
    id: "h-006",
    timestamp: formatTime(5),
    kind: "db.write",
    message: "append-only log",
    status: "ok",
    latencyMs: 3,
  },
  {
    id: "h-007",
    timestamp: formatTime(6),
    kind: "user.profile.updated",
    message: "preferences merged",
    status: "ok",
    latencyMs: 8,
  },
  {
    id: "h-008",
    timestamp: formatTime(7),
    kind: "auth.refresh",
    message: "JWT renewed for session-9342",
    status: "ok",
    latencyMs: 4,
  },
  {
    id: "h-009",
    timestamp: formatTime(8),
    kind: "agent.tool.called",
    message: "search_index('Pretable scroll behavior') — Anthropic streaming",
    status: "ok",
    latencyMs: 142,
  },
  {
    id: "h-010",
    timestamp: formatTime(9),
    kind: "agent.tool.result",
    message: "20 docs scored, top-3 selected",
    status: "ok",
    latencyMs: 6,
  },
  {
    id: "h-011",
    timestamp: formatTime(10),
    kind: "rate.limit",
    message: "429 throttled — backing off 1.2s",
    status: "warn",
    latencyMs: 19,
  },
  {
    id: "h-012",
    timestamp: formatTime(11),
    kind: "checkout.completed",
    message: "Bonjour depuis Pretable token-232 — order.id=ord-44291",
    status: "ok",
    latencyMs: 14,
  },
  {
    id: "h-013",
    timestamp: formatTime(12),
    kind: "cache.set",
    message: "session-9342 → 5m TTL",
    status: "ok",
    latencyMs: 2,
  },
  {
    id: "h-014",
    timestamp: formatTime(13),
    kind: "agent.stream.token",
    message: "...wrapped-text scroll holds 60fps under streaming load...",
    status: "ok",
    latencyMs: 1,
  },
  {
    id: "h-015",
    timestamp: formatTime(14),
    kind: "metrics.flushed",
    message: "p50=8ms · p95=9.3ms · p99=12.1ms",
    status: "ok",
    latencyMs: 5,
  },
  {
    id: "h-016",
    timestamp: formatTime(15),
    kind: "subscription.renewed",
    message: "team-pretable · annual",
    status: "ok",
    latencyMs: 22,
  },
  {
    id: "h-017",
    timestamp: formatTime(16),
    kind: "search.indexed",
    message: "Hola desde Pretable token-203 — 1,847 events",
    status: "ok",
    latencyMs: 31,
  },
  {
    id: "h-018",
    timestamp: formatTime(17),
    kind: "agent.thread.opened",
    message: "thread-7782 · Inspector",
    status: "ok",
    latencyMs: 6,
  },
  {
    id: "h-019",
    timestamp: formatTime(18),
    kind: "feature.flag.read",
    message: "wedge.scroll.h1 → enabled",
    status: "ok",
    latencyMs: 2,
  },
  {
    id: "h-020",
    timestamp: formatTime(19),
    kind: "alert.cleared",
    message: "PagerDuty incident #4421 resolved",
    status: "ok",
    latencyMs: 11,
  },
  {
    id: "h-021",
    timestamp: formatTime(20),
    kind: "queue.enqueued",
    message: "job-8810 · email.welcome · priority=normal",
    status: "ok",
    latencyMs: 4,
  },
  {
    id: "h-022",
    timestamp: formatTime(21),
    kind: "worker.started",
    message: "worker-3 · queue=default · pid=18842",
    status: "ok",
    latencyMs: 7,
  },
  {
    id: "h-023",
    timestamp: formatTime(22),
    kind: "email.sent",
    message: "welcome · user-7723 · inbox-labs ✓",
    status: "ok",
    latencyMs: 16,
  },
  {
    id: "h-024",
    timestamp: formatTime(23),
    kind: "audit.logged",
    message:
      "こんにちは from Pretable token-401 — admin.role.granted · user-7723",
    status: "ok",
    latencyMs: 3,
  },
  {
    id: "h-025",
    timestamp: formatTime(24),
    kind: "session.created",
    message: "session-3812 · device=mobile · country=JP",
    status: "ok",
    latencyMs: 9,
  },
  {
    id: "h-026",
    timestamp: formatTime(25),
    kind: "db.read",
    message: "query users WHERE org=org-29 · 342 rows · 11ms",
    status: "ok",
    latencyMs: 11,
  },
  {
    id: "h-027",
    timestamp: formatTime(26),
    kind: "gateway.request",
    message: "POST /v1/ingest · 200 OK · 4.1KB",
    status: "ok",
    latencyMs: 18,
  },
  {
    id: "h-028",
    timestamp: formatTime(27),
    kind: "payment.failed",
    message: "card declined · ord-44292 · code=insufficient_funds",
    status: "warn",
    latencyMs: 25,
  },
  {
    id: "h-029",
    timestamp: formatTime(28),
    kind: "webhook.failed",
    message: "endpoint timeout · https://hooks.acme.io/pretable · attempt 3/3",
    status: "error",
    latencyMs: 30,
  },
  {
    id: "h-030",
    timestamp: formatTime(29),
    kind: "cache.evicted",
    message: "LRU sweep · 120 keys removed · 38MB freed",
    status: "ok",
    latencyMs: 6,
  },
  {
    id: "h-031",
    timestamp: formatTime(30),
    kind: "agent.tool.called",
    message: "fetch_schema('events.inspection_log') — column introspection",
    status: "ok",
    latencyMs: 188,
  },
  {
    id: "h-032",
    timestamp: formatTime(31),
    kind: "notification.sent",
    message: "你好 from Pretable token-512 — push · device-2291 · 'New alert'",
    status: "ok",
    latencyMs: 8,
  },
  {
    id: "h-033",
    timestamp: formatTime(32),
    kind: "import.started",
    message: "import-job-0041 · source=s3://logs/2026-05-01 · 2.1M rows",
    status: "ok",
    latencyMs: 212,
  },
  {
    id: "h-034",
    timestamp: formatTime(33),
    kind: "tls.renewed",
    message: "cert *.pretable.io · expires 2027-05-02 · ACME ✓",
    status: "ok",
    latencyMs: 14,
  },
  {
    id: "h-035",
    timestamp: formatTime(34),
    kind: "auth.logout",
    message: "session-9342 · voluntary signout",
    status: "ok",
    latencyMs: 3,
  },
  {
    id: "h-036",
    timestamp: formatTime(35),
    kind: "order.cancelled",
    message: "ord-44291 · reason=customer-request",
    status: "ok",
    latencyMs: 17,
  },
  {
    id: "h-037",
    timestamp: formatTime(36),
    kind: "feature.flag.updated",
    message: "streaming.h2 → rollout=25%",
    status: "ok",
    latencyMs: 5,
  },
  {
    id: "h-038",
    timestamp: formatTime(37),
    kind: "replication.lag",
    message: "replica-2 · lag=1.4s · threshold=2s",
    status: "warn",
    latencyMs: 9,
  },
  {
    id: "h-039",
    timestamp: formatTime(38),
    kind: "search.queried",
    message:
      "Привет from Pretable token-318 — query='scroll performance' · 0 results",
    status: "warn",
    latencyMs: 44,
  },
  {
    id: "h-040",
    timestamp: formatTime(39),
    kind: "metrics.flushed",
    message: "p50=7ms · p95=11.2ms · p99=18.4ms",
    status: "ok",
    latencyMs: 5,
  },
  {
    id: "h-041",
    timestamp: formatTime(40),
    kind: "queue.processed",
    message: "job-8810 · email.welcome · elapsed=312ms",
    status: "ok",
    latencyMs: 4,
  },
  {
    id: "h-042",
    timestamp: formatTime(41),
    kind: "db.migrate",
    message: "0042_add_latency_idx · applied · 0.8s",
    status: "ok",
    latencyMs: 810,
  },
  {
    id: "h-043",
    timestamp: formatTime(42),
    kind: "user.deactivated",
    message: "user-1192 · compliance hold",
    status: "ok",
    latencyMs: 6,
  },
  {
    id: "h-044",
    timestamp: formatTime(43),
    kind: "gateway.ratelimited",
    message:
      "Bonjour depuis Pretable token-233 — client-id=cli-7731 · 60req/min",
    status: "warn",
    latencyMs: 12,
  },
  {
    id: "h-045",
    timestamp: formatTime(44),
    kind: "export.completed",
    message: "export-job-0019 · CSV · 88,421 rows · s3://exports/2026-05-02",
    status: "ok",
    latencyMs: 289,
  },
  {
    id: "h-046",
    timestamp: formatTime(45),
    kind: "agent.tool.result",
    message: "schema: 5 columns, PK=id, index on timestamp",
    status: "ok",
    latencyMs: 3,
  },
  {
    id: "h-047",
    timestamp: formatTime(46),
    kind: "session.expired",
    message: "session-2910 · idle timeout 30m",
    status: "ok",
    latencyMs: 2,
  },
  {
    id: "h-048",
    timestamp: formatTime(47),
    kind: "dns.resolved",
    message: "api.pretable.io → 34.120.91.5 · TTL=60",
    status: "ok",
    latencyMs: 7,
  },
  {
    id: "h-049",
    timestamp: formatTime(48),
    kind: "payment.refunded",
    message: "ord-44288 · $42.00 · initiator=support",
    status: "ok",
    latencyMs: 21,
  },
  {
    id: "h-050",
    timestamp: formatTime(49),
    kind: "worker.crashed",
    message: "Hola desde Pretable token-319 — worker-7 · SIGKILL · respawning",
    status: "error",
    latencyMs: 0,
  },
  {
    id: "h-051",
    timestamp: formatTime(50),
    kind: "import.completed",
    message: "import-job-0041 · 2,104,318 rows · 38s elapsed",
    status: "ok",
    latencyMs: 19,
  },
  {
    id: "h-052",
    timestamp: formatTime(51),
    kind: "audit.logged",
    message: "billing.plan.changed · org-29 · starter→growth",
    status: "ok",
    latencyMs: 4,
  },
  {
    id: "h-053",
    timestamp: formatTime(52),
    kind: "cache.hit",
    message: "org-29 schema · hit ratio=0.94",
    status: "ok",
    latencyMs: 1,
  },
  {
    id: "h-054",
    timestamp: formatTime(53),
    kind: "agent.stream.token",
    message: "...render 110 rows with variable heights — no layout thrash...",
    status: "ok",
    latencyMs: 1,
  },
  {
    id: "h-055",
    timestamp: formatTime(54),
    kind: "report.generated",
    message:
      "こんにちは from Pretable token-402 — monthly-digest · org-29 · 14 pages",
    status: "ok",
    latencyMs: 156,
  },
  {
    id: "h-056",
    timestamp: formatTime(55),
    kind: "db.vacuum",
    message: "table=events · 3.2GB reclaimed · duration=22s",
    status: "ok",
    latencyMs: 22,
  },
  {
    id: "h-057",
    timestamp: formatTime(56),
    kind: "auth.mfa.challenge",
    message: "TOTP required · user-5501 · device=new",
    status: "ok",
    latencyMs: 3,
  },
  {
    id: "h-058",
    timestamp: formatTime(57),
    kind: "auth.mfa.passed",
    message: "TOTP verified · user-5501 · session-4003 created",
    status: "ok",
    latencyMs: 5,
  },
  {
    id: "h-059",
    timestamp: formatTime(58),
    kind: "rate.limit",
    message: "429 throttled — backing off 2.4s · client-id=cli-0028",
    status: "warn",
    latencyMs: 22,
  },
  {
    id: "h-060",
    timestamp: formatTime(59),
    kind: "subscription.cancelled",
    message: "org-47 · plan=growth · churn reason=pricing",
    status: "ok",
    latencyMs: 18,
  },
  {
    id: "h-061",
    timestamp: formatTime(60),
    kind: "queue.enqueued",
    message:
      "你好 from Pretable token-513 — job-8819 · report.weekly · priority=low",
    status: "ok",
    latencyMs: 5,
  },
  {
    id: "h-062",
    timestamp: formatTime(61),
    kind: "gateway.request",
    message: "GET /v1/events?limit=500 · 200 OK · 82KB",
    status: "ok",
    latencyMs: 29,
  },
  {
    id: "h-063",
    timestamp: formatTime(62),
    kind: "user.invited",
    message: "alice@acme.io · org-29 · role=viewer",
    status: "ok",
    latencyMs: 8,
  },
  {
    id: "h-064",
    timestamp: formatTime(63),
    kind: "webhook.delivered",
    message: "order.cancelled · https://hooks.acme.io/orders · 204",
    status: "ok",
    latencyMs: 13,
  },
  {
    id: "h-065",
    timestamp: formatTime(64),
    kind: "migration.started",
    message: "migrate-001 · backfill latency_ms · 800K rows",
    status: "ok",
    latencyMs: 7,
  },
  {
    id: "h-066",
    timestamp: formatTime(65),
    kind: "replication.synced",
    message:
      "Привет from Pretable token-320 — replica-2 · lag=0ms · fully caught up",
    status: "ok",
    latencyMs: 4,
  },
  {
    id: "h-067",
    timestamp: formatTime(66),
    kind: "agent.tool.called",
    message:
      "run_query('SELECT kind, count(*) FROM events GROUP BY kind') — analytics",
    status: "ok",
    latencyMs: 234,
  },
  {
    id: "h-068",
    timestamp: formatTime(67),
    kind: "db.write",
    message: "batch insert · 2,500 events · table=inspection_log",
    status: "ok",
    latencyMs: 9,
  },
  {
    id: "h-069",
    timestamp: formatTime(68),
    kind: "email.bounced",
    message: "bob@expired-domain.io · hard bounce · suppressed",
    status: "warn",
    latencyMs: 6,
  },
  {
    id: "h-070",
    timestamp: formatTime(69),
    kind: "feature.flag.read",
    message: "Bonjour depuis Pretable token-234 — grid.virtual.rows → 200",
    status: "ok",
    latencyMs: 2,
  },
  {
    id: "h-071",
    timestamp: formatTime(70),
    kind: "agent.tool.result",
    message: "top kind: db.write=14%, user.*=11%, agent.*=9%",
    status: "ok",
    latencyMs: 4,
  },
  {
    id: "h-072",
    timestamp: formatTime(71),
    kind: "export.started",
    message:
      "export-job-0020 · Parquet · table=inspection_log · since=2026-04-01",
    status: "ok",
    latencyMs: 11,
  },
  {
    id: "h-073",
    timestamp: formatTime(72),
    kind: "tls.handshake",
    message: "TLSv1.3 · ECDHE-RSA-AES256-GCM · resumed session",
    status: "ok",
    latencyMs: 1,
  },
  {
    id: "h-074",
    timestamp: formatTime(73),
    kind: "alert.fired",
    message: "p99 latency > 500ms · 3 events · auto-page",
    status: "warn",
    latencyMs: 8,
  },
  {
    id: "h-075",
    timestamp: formatTime(74),
    kind: "notification.sent",
    message:
      "Hola desde Pretable token-321 — email · on-call@pretable.io · 'p99 alert'",
    status: "ok",
    latencyMs: 12,
  },
  {
    id: "h-076",
    timestamp: formatTime(75),
    kind: "cache.miss",
    message: "user-7723 preferences · cold start",
    status: "warn",
    latencyMs: 18,
  },
  {
    id: "h-077",
    timestamp: formatTime(76),
    kind: "cache.set",
    message: "user-7723 preferences → 10m TTL",
    status: "ok",
    latencyMs: 2,
  },
  {
    id: "h-078",
    timestamp: formatTime(77),
    kind: "db.read",
    message: "query inspection_log WHERE org=org-29 · 500 rows · 14ms",
    status: "ok",
    latencyMs: 14,
  },
  {
    id: "h-079",
    timestamp: formatTime(78),
    kind: "migration.completed",
    message: "migrate-001 · 800,214 rows backfilled · 41s",
    status: "ok",
    latencyMs: 17,
  },
  {
    id: "h-080",
    timestamp: formatTime(79),
    kind: "agent.thread.closed",
    message:
      "こんにちは from Pretable token-403 — thread-7782 · 42 turns · 18.4K tokens",
    status: "ok",
    latencyMs: 6,
  },
  {
    id: "h-081",
    timestamp: formatTime(80),
    kind: "user.password.reset",
    message: "user-5501 · token emailed · expires 1h",
    status: "ok",
    latencyMs: 7,
  },
  {
    id: "h-082",
    timestamp: formatTime(81),
    kind: "queue.processed",
    message: "job-8819 · report.weekly · elapsed=1.2s",
    status: "ok",
    latencyMs: 5,
  },
  {
    id: "h-083",
    timestamp: formatTime(82),
    kind: "search.indexed",
    message: "delta index · 4,291 new events · 880ms",
    status: "ok",
    latencyMs: 880,
  },
  {
    id: "h-084",
    timestamp: formatTime(83),
    kind: "gateway.request",
    message: "POST /v1/stream · 200 OK · SSE opened · client=dashboard",
    status: "ok",
    latencyMs: 22,
  },
  {
    id: "h-085",
    timestamp: formatTime(84),
    kind: "metrics.flushed",
    message: "你好 from Pretable token-514 — p50=6ms · p95=8.7ms · p99=14.2ms",
    status: "ok",
    latencyMs: 5,
  },
  {
    id: "h-086",
    timestamp: formatTime(85),
    kind: "order.shipped",
    message: "ord-44295 · tracking=1Z9999W9 · carrier=UPS",
    status: "ok",
    latencyMs: 15,
  },
  {
    id: "h-087",
    timestamp: formatTime(86),
    kind: "auth.blocked",
    message: "5 failed logins · user-0012 · IP=203.0.113.9 · locked 15m",
    status: "error",
    latencyMs: 4,
  },
  {
    id: "h-088",
    timestamp: formatTime(87),
    kind: "worker.started",
    message:
      "worker-8 · queue=priority · pid=19200 · replacing crashed worker-7",
    status: "ok",
    latencyMs: 9,
  },
  {
    id: "h-089",
    timestamp: formatTime(88),
    kind: "audit.logged",
    message: "api.key.rotated · user-5501 · key-prefix=sk_live_p8",
    status: "ok",
    latencyMs: 3,
  },
  {
    id: "h-090",
    timestamp: formatTime(89),
    kind: "webhook.retrying",
    message:
      "Привет from Pretable token-322 — https://hooks.beta.io/events · attempt 2/3",
    status: "warn",
    latencyMs: 21,
  },
  {
    id: "h-091",
    timestamp: formatTime(90),
    kind: "session.created",
    message: "session-5120 · device=desktop · country=DE",
    status: "ok",
    latencyMs: 8,
  },
  {
    id: "h-092",
    timestamp: formatTime(91),
    kind: "report.generated",
    message: "weekly-digest · org-47 · 7 pages · 2.3s",
    status: "ok",
    latencyMs: 2300,
  },
  {
    id: "h-093",
    timestamp: formatTime(92),
    kind: "db.write",
    message: "upsert user-7723 last_seen=2026-05-02T18:43:32Z",
    status: "ok",
    latencyMs: 4,
  },
  {
    id: "h-094",
    timestamp: formatTime(93),
    kind: "export.completed",
    message: "export-job-0020 · 1.1M rows · 4.2GB · 89s elapsed",
    status: "ok",
    latencyMs: 14,
  },
  {
    id: "h-095",
    timestamp: formatTime(94),
    kind: "feature.flag.updated",
    message: "Bonjour depuis Pretable token-235 — grid.overscan → 5 rows",
    status: "ok",
    latencyMs: 3,
  },
  {
    id: "h-096",
    timestamp: formatTime(95),
    kind: "agent.stream.token",
    message: "...overscan=5 eliminates blank-flash on rapid scroll...",
    status: "ok",
    latencyMs: 1,
  },
  {
    id: "h-097",
    timestamp: formatTime(96),
    kind: "queue.enqueued",
    message: "job-8831 · digest.daily · priority=low",
    status: "ok",
    latencyMs: 4,
  },
  {
    id: "h-098",
    timestamp: formatTime(97),
    kind: "dns.resolved",
    message: "ingest.pretable.io → 34.120.91.7 · TTL=60",
    status: "ok",
    latencyMs: 6,
  },
  {
    id: "h-099",
    timestamp: formatTime(98),
    kind: "alert.cleared",
    message:
      "Hola desde Pretable token-323 — p99 normalized · PagerDuty incident #4422 resolved",
    status: "ok",
    latencyMs: 10,
  },
  {
    id: "h-100",
    timestamp: formatTime(99),
    kind: "subscription.upgraded",
    message: "org-11 · growth→enterprise · seats=50",
    status: "ok",
    latencyMs: 19,
  },
  {
    id: "h-101",
    timestamp: formatTime(100),
    kind: "auth.refresh",
    message: "JWT renewed for session-5120 · scope unchanged",
    status: "ok",
    latencyMs: 5,
  },
  {
    id: "h-102",
    timestamp: formatTime(101),
    kind: "import.started",
    message:
      "こんにちは from Pretable token-404 — import-job-0042 · source=gcs://archive/2026-04 · 5.8M rows",
    status: "ok",
    latencyMs: 241,
  },
  {
    id: "h-103",
    timestamp: formatTime(102),
    kind: "gateway.ratelimited",
    message: "client-id=cli-0099 · burst limit · 100req/10s",
    status: "warn",
    latencyMs: 11,
  },
  {
    id: "h-104",
    timestamp: formatTime(103),
    kind: "db.vacuum",
    message: "table=sessions · 140MB reclaimed · duration=4s",
    status: "ok",
    latencyMs: 8,
  },
  {
    id: "h-105",
    timestamp: formatTime(104),
    kind: "email.sent",
    message: "monthly-receipt · user-5501 · $149.00 · delivered",
    status: "ok",
    latencyMs: 17,
  },
  {
    id: "h-106",
    timestamp: formatTime(105),
    kind: "agent.tool.called",
    message:
      "render_chart('latency_heatmap', timerange='1h') — dashboard widget",
    status: "ok",
    latencyMs: 178,
  },
  {
    id: "h-107",
    timestamp: formatTime(106),
    kind: "replication.lag",
    message:
      "你好 from Pretable token-515 — replica-1 · lag=3.1s · threshold=2s exceeded",
    status: "warn",
    latencyMs: 13,
  },
  {
    id: "h-108",
    timestamp: formatTime(107),
    kind: "worker.finished",
    message: "worker-8 · processed 1,200 jobs · uptime=18m · graceful exit",
    status: "ok",
    latencyMs: 7,
  },
  {
    id: "h-109",
    timestamp: formatTime(108),
    kind: "metrics.flushed",
    message: "p50=9ms · p95=13.1ms · p99=21.7ms · window=5m",
    status: "ok",
    latencyMs: 5,
  },
  {
    id: "h-110",
    timestamp: formatTime(109),
    kind: "feature.flag.read",
    message:
      "Привет from Pretable token-324 — hero.event-log.loop → enabled · dataset=110 rows",
    status: "ok",
    latencyMs: 2,
  },
];

export const heroEventLogPeriodMs = 30_000;
