/**
 * Exhaustive operator-semantics sweep for `compileFilterPredicate` — the
 * compile step that specializes one `(value) => boolean` closure per runtime
 * filter at plan construction. Every (column type, operator) pair in
 * `FILTER_OPERATORS` appears at least once, and every expectation is pinned
 * as a LITERAL derived from the pre-refactor `evaluateFilter` semantics —
 * never generated by calling the code under test. The coverage test at the
 * bottom fails if `FILTER_OPERATORS` grows a pair this sweep doesn't cover.
 */

import { describe, expect, test } from "vitest";

import { FILTER_OPERATORS, compileFilterPredicate } from "../compiled-query";

interface SweepEntry {
  readonly type: keyof typeof FILTER_OPERATORS;
  readonly operator: string;
  readonly operand?: unknown;
  /** [cell value, expected verdict] — expectations are pinned literals. */
  readonly cases: readonly (readonly [unknown, boolean])[];
}

/**
 * `isEmpty` semantics are type-independent (`isEmptyValue`): null, undefined,
 * NaN, and whitespace-only strings are empty; everything else is not.
 */
const EMPTY_CASES: readonly (readonly [unknown, boolean])[] = [
  [null, true],
  [undefined, true],
  ["", true],
  ["   ", true],
  [Number.NaN, true],
  [0, false],
  ["x", false],
  [false, false],
  [new Date(0), false],
];

const emptinessEntries: SweepEntry[] = (
  ["text", "number", "date", "enum", "boolean"] as const
).flatMap((type) => [
  { type, operator: "isEmpty", cases: EMPTY_CASES },
  {
    type,
    operator: "isNotEmpty",
    cases: EMPTY_CASES.map(([value, expected]) => [value, !expected] as const),
  },
]);

const MARCH_15_NOON_MS = Date.UTC(2024, 2, 15, 13, 45);

const SWEEP: readonly SweepEntry[] = [
  ...emptinessEntries,

  // ── text ── cell and needle both String(...).toLocaleLowerCase(); a
  // nullish cell folds to "".
  {
    type: "text",
    operator: "contains",
    operand: "Ab",
    cases: [
      ["cab", true],
      ["AB", true],
      ["b", false],
      ["", false],
      [null, false],
      [undefined, false],
      [123, false],
    ],
  },
  {
    type: "text",
    operator: "contains",
    operand: "",
    // Every cell contains the empty needle — including a nullish cell.
    cases: [
      [null, true],
      ["x", true],
      ["", true],
    ],
  },
  {
    type: "text",
    operator: "notContains",
    operand: "Ab",
    cases: [
      ["cab", false],
      ["b", true],
      [null, true],
    ],
  },
  {
    type: "text",
    operator: "equals",
    operand: "Foo",
    cases: [
      ["foo", true],
      ["FOO", true],
      [" foo", false],
      ["foo ", false],
      [null, false],
      ["", false],
    ],
  },
  {
    type: "text",
    operator: "equals",
    operand: "",
    // A nullish cell folds to "" and therefore EQUALS the empty needle.
    cases: [
      [null, true],
      [undefined, true],
      ["", true],
      ["x", false],
    ],
  },
  {
    type: "text",
    operator: "notEquals",
    operand: "foo",
    cases: [
      ["bar", true],
      ["FOO", false],
      [null, true],
      ["", true],
    ],
  },
  {
    type: "text",
    operator: "startsWith",
    operand: "Ca",
    cases: [
      ["Cab", true],
      ["cAt", true],
      ["aCa", false],
      [null, false],
    ],
  },
  {
    type: "text",
    operator: "endsWith",
    operand: "at",
    cases: [
      ["Cat", true],
      ["AT", true],
      ["atx", false],
      [null, false],
    ],
  },

  // ── number ── a non-number or NaN cell fails EVERY operator, including
  // notEquals.
  {
    type: "number",
    operator: "equals",
    operand: 5,
    cases: [
      [5, true],
      [4, false],
      [Number.NaN, false],
      [null, false],
      ["5", false],
      [undefined, false],
    ],
  },
  {
    type: "number",
    operator: "notEquals",
    operand: 5,
    cases: [
      [4, true],
      [5, false],
      [Number.NaN, false],
      [null, false],
      ["5", false],
    ],
  },
  {
    type: "number",
    operator: "gt",
    operand: 5,
    cases: [
      [6, true],
      [5.000001, true],
      [5, false],
      [4, false],
      [Number.NaN, false],
      [Number.POSITIVE_INFINITY, true],
    ],
  },
  {
    type: "number",
    operator: "gte",
    operand: 5,
    cases: [
      [5, true],
      [6, true],
      [4.999, false],
      [null, false],
    ],
  },
  {
    type: "number",
    operator: "lt",
    operand: 5,
    cases: [
      [4, true],
      [5, false],
      [Number.NEGATIVE_INFINITY, true],
      [Number.NaN, false],
    ],
  },
  {
    type: "number",
    operator: "lte",
    operand: 5,
    cases: [
      [5, true],
      [4, true],
      [6, false],
      [null, false],
    ],
  },
  {
    type: "number",
    operator: "between",
    operand: [3, 7],
    // Inclusive at BOTH bounds — the boundary cases the mutation test leans on.
    cases: [
      [3, true],
      [7, true],
      [5, true],
      [2.9999, false],
      [7.0001, false],
      [Number.NaN, false],
      [null, false],
      ["5", false],
    ],
  },
  {
    type: "number",
    operator: "between",
    operand: [7, 3],
    // Reversed range normalizes via min/max; still inclusive at both bounds.
    cases: [
      [5, true],
      [3, true],
      [7, true],
      [2, false],
      [8, false],
    ],
  },

  // ── date ── both sides collapse to a UTC calendar day via `toDayMs`; an
  // unparsable cell fails every operator.
  {
    type: "date",
    operator: "on",
    operand: "2024-03-15",
    cases: [
      ["2024-03-15", true],
      ["2024-03-15T23:59:59Z", true],
      [MARCH_15_NOON_MS, true],
      [new Date(Date.UTC(2024, 2, 15, 5)), true],
      ["2024-03-16", false],
      // -05:00 pushes the instant into the NEXT UTC day.
      ["2024-03-15T23:00:00-05:00", false],
      ["garbage", false],
      [null, false],
      ["", false],
    ],
  },
  {
    type: "date",
    operator: "before",
    operand: "2024-03-15",
    cases: [
      ["2024-03-14", true],
      ["2024-03-14T23:59:59Z", true],
      ["2024-03-15", false],
      ["2024-03-16", false],
      [null, false],
      ["junk", false],
    ],
  },
  {
    type: "date",
    operator: "after",
    operand: "2024-03-15",
    cases: [
      ["2024-03-16", true],
      ["2024-03-15", false],
      ["2024-03-15T23:59:59Z", false],
      ["2024-03-14", false],
      [null, false],
    ],
  },
  {
    type: "date",
    operator: "dateBetween",
    operand: ["2024-03-10", "2024-03-20"],
    // Inclusive at both DAY bounds; a time-of-day on the bound day still hits.
    cases: [
      ["2024-03-10", true],
      ["2024-03-20", true],
      ["2024-03-20T23:59:59Z", true],
      ["2024-03-15", true],
      ["2024-03-09", false],
      ["2024-03-21", false],
      [null, false],
      ["x", false],
    ],
  },
  {
    type: "date",
    operator: "dateBetween",
    operand: ["2024-03-20", "2024-03-10"],
    cases: [
      ["2024-03-15", true],
      ["2024-03-10", true],
      ["2024-03-09", false],
    ],
  },
  {
    type: "date",
    operator: "dateBetween",
    operand: [new Date(Date.UTC(2024, 2, 10)), new Date(Date.UTC(2024, 2, 20))],
    cases: [
      ["2024-03-15", true],
      ["2024-03-21", false],
    ],
  },

  // ── enum ── membership over String(...) coercion of BOTH sides; an empty
  // selection matches everything regardless of direction.
  {
    type: "enum",
    operator: "isAnyOf",
    operand: ["a", "b"],
    cases: [
      ["a", true],
      ["b", true],
      ["c", false],
      [null, false],
      [undefined, false],
      ["", false],
    ],
  },
  {
    type: "enum",
    operator: "isAnyOf",
    operand: [1, "2"],
    cases: [
      [1, true],
      ["1", true],
      [2, true],
      [3, false],
    ],
  },
  {
    type: "enum",
    operator: "isAnyOf",
    operand: [null],
    // String(null) === "null" on both sides.
    cases: [
      [null, true],
      ["null", true],
      ["x", false],
    ],
  },
  {
    type: "enum",
    operator: "isAnyOf",
    operand: [],
    cases: [
      ["x", true],
      [null, true],
    ],
  },
  {
    type: "enum",
    operator: "isNoneOf",
    operand: ["a"],
    cases: [
      ["a", false],
      ["b", true],
      [null, true],
    ],
  },
  {
    type: "enum",
    operator: "isNoneOf",
    operand: [],
    // Empty selection short-circuits to TRUE before direction applies.
    cases: [["a", true]],
  },

  // ── boolean ── membership over `booleanValue` coercion of both sides.
  {
    type: "boolean",
    operator: "isAnyOf",
    operand: [true],
    cases: [
      [true, true],
      ["true", true],
      [1, true],
      ["1", true],
      ["yes", true], // Boolean("yes") === true
      [false, false],
      [0, false],
      ["false", false],
      [null, false],
      [Number.NaN, false],
    ],
  },
  {
    type: "boolean",
    operator: "isAnyOf",
    operand: ["false"],
    cases: [
      [false, true],
      [0, true],
      ["0", true],
      ["", true],
      [null, true], // Boolean(null) === false
      [true, false],
    ],
  },
  {
    type: "boolean",
    operator: "isAnyOf",
    operand: [],
    cases: [
      [true, true],
      [null, true],
    ],
  },
  {
    type: "boolean",
    operator: "isNoneOf",
    operand: [true],
    cases: [
      [false, true],
      [null, true],
      [true, false],
      ["1", false],
    ],
  },
  {
    type: "boolean",
    operator: "isNoneOf",
    operand: [],
    cases: [[false, true]],
  },
];

describe("compileFilterPredicate", () => {
  for (const entry of SWEEP) {
    const operandLabel =
      entry.operand === undefined ? "" : ` ${JSON.stringify(entry.operand)}`;
    test(`${entry.type} ${entry.operator}${operandLabel}`, () => {
      const predicate = compileFilterPredicate(
        { columnId: "c", operator: entry.operator, value: entry.operand },
        { type: entry.type },
      );
      for (const [value, expected] of entry.cases) {
        expect(predicate(value), `cell ${String(value)}`).toBe(expected);
      }
    });
  }

  test("a compiled predicate is a reusable closure", () => {
    const predicate = compileFilterPredicate(
      { columnId: "c", operator: "between", value: [3, 7] },
      { type: "number" },
    );
    expect(predicate(3)).toBe(true);
    expect(predicate(3)).toBe(true);
    expect(predicate(8)).toBe(false);
  });

  test("sweep covers every (type, operator) pair in FILTER_OPERATORS", () => {
    const expected = new Set<string>();
    for (const [type, operators] of Object.entries(FILTER_OPERATORS)) {
      for (const operator of operators) expected.add(`${type}:${operator}`);
    }
    // 8 text + 9 number + 6 date + 4 enum + 4 boolean.
    expect(expected.size).toBe(31);
    const covered = new Set(
      SWEEP.map((entry) => `${entry.type}:${entry.operator}`),
    );
    expect([...covered].sort()).toEqual([...expected].sort());
  });
});
